global using System.Text;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using GestioneSagre.Messaging.Abstractions;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using RabbitMQ.Client;
global using RabbitMQ.Client.Events;
